### ISSUE TITLE
"Loading from the chain, please wait..." show forever if input dao name not existed.

### ISSUE THREAD

**Issue by rony2818** [near-daos/sputnik-dao-2-ui-reference#12]
Discord or Telegram handle
Telegram handle: @RonyLe2818

Describe the bug
"Loading from the chain, please wait..." show forever if input dao name not existed.

To Reproduce

modifying the following link to have its address: Ex: [https://testnet-v2.sputnik.fund/#/rony-dào](https://testnet-v2.sputnik.fund/#/rony-d%C3%A0o)
Page always show "Loading from the chain, please wait..."
Go home page (https://testnet-v2.sputnik.fund/) "Loading from the chain, please wait..." still show. Can't do anything.
This bug disappear after remove local storage by manual.
Expected behavior
Shouldn't save data to local storage if user input Dao name not exited.

Screenshots
<img width="1695" alt="Screen Shot 2022-05-10 at 20 02 39" src="https://user-images.githubusercontent.com/11047732/167763557-7eab988d-754e-44b2-aac6-7fb1ed62273b.png">

**Comment by AngelBlock** [comment]
This should be fixed now.
