### ISSUE TITLE
Add Payout request doesn't work for fungible token

### ISSUE THREAD

**Issue by frankbraun** [near-daos/sputnik-dao-2-ui-reference#2]
It seems that making a payout request for a fungible token doesn't work on https://v2.sputnik.fund for tokens which are not from tkn.farm.

![image](https://user-images.githubusercontent.com/1965208/133696164-37eeb10d-6139-4b8f-8819-e4157478fe3f.png)

The "submit" button is not responsive. Console output:

![image](https://user-images.githubusercontent.com/1965208/133696230-98c5bcd7-6952-4ed9-a967-76d88e73e90b.png)

**Comment by AngelBlock** [comment]
@frankbraun Tested and working, can you elaborate please?
