### ISSUE TITLE
Remove all hard coded occurences of array entries for DAO roles

### ISSUE THREAD

**Issue by Tarnadas** [near-daos/sputnik-dao-2-ui-reference#6]
Example fix: #5

There are various occurences in the code like `daoPolicy.roles[1]`, but they assume, that there exist exactly two groups in the DAO.
DAOs with more groups or DAOs without an "Everyone" role would therefore have errors.

All occurences of hard coded array entries should be replaces with a loop.

**Comment by AngelBlock** [comment]
@Tarnadas Apologies for not answering earlier, it's been extremely busy week. 

Is this still relevant considering AstroDAO release?

**Comment by Tarnadas** [comment]
Hey, we have been mostly moving to AstroDAO, but I wasn’t sure how this UI implementation will be maintained, so I wanted to report it anyway

**Comment by AngelBlock** [comment]
> Hey, we have been mostly moving to AstroDAO, but I wasn’t sure how this UI implementation will be maintained, so I wanted to report it anyway

Thanks, appreciate it. I'll see if I can fix/push it when have a spare time. The temp workaround has already been applied.

**Comment by AngelBlock** [comment]
Fixed in a72809a8189ca088011dbea1a33f67d2a96e4dfc

**Comment by Tarnadas** [comment]
Hey @AngelBlock,
I see that you took my changes from #5, but it's not the fix for the whole issue. I only applied the fix to one occurence.
I was also hoping to have the PR merged or co-authored, so that I show up in the contributor list

**Comment by AngelBlock** [comment]
> Hey @AngelBlock,
> I see that you took my changes from #5, but it's not the fix for the whole issue. I only applied the fix to one occurence.
> I was also hoping to have the PR merged or co-authored, so that I show up in the contributor list

Hey, I had some issues resolving the conflicts, so it was easier to integrated the code, apologies. The repo has moved to a new organisation, can you fork it again or **make sure your fork still works after the move** and kindly do the other occurrences into PR and I'll merge them immediately. Hope this will be ok with you.
